# Generated by Django 5.0.4 on 2024-04-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=None, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=None, verbose_name='Дата обновления'),
        ),
    ]
