# Generated by Django 5.0.4 on 2024-04-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_remove_product_discount_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images/', verbose_name='Изображение'),
        ),
    ]
