# Generated by Django 5.0.4 on 2024-04-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id',)},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Идентификатор в URL'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
