# Generated by Django 5.0.4 on 2024-04-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetail_price_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
